### ISSUE TITLE
打开rviz之后挂掉

### ISSUE THREAD

**Issue by ouyangandy** [plumewind/slam_simulator#3]
`simulator: /usr/local/include/eigen3/Eigen/src/Core/Redux.h:413: typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_max_op<double, double>; Derived = Eigen::PartialReduxExpr<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::Matrix<double, -1, -1> >, Eigen::internal::member_sum<double>, 0>; typename Eigen::internal::traits<T>::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.
[simulator-2] process has died [pid 14520, exit code -6, cmd /home/minghua/catkin_ekf/devel/lib/slam_simulator/simulator __name:=simulator __log:=/home/minghua/.ros/log/1fdc52cc-a153-11e9-80e2-000c29d62a5d/simulator-2.log].
log file: /home/minghua/.ros/log/1fdc52cc-a153-11e9-80e2-000c29d62a5d/simulator-2*.log

`
作者你好，当我运行ekf的时候出现上述错误，不知道该如何解决。麻烦您能帮忙看一下吗？打开rviz之后就挂掉了。

**Comment by plumewind** [comment]
你运行的是哪个版本？只有ekf的吗？

**Comment by ouyangandy** [comment]
> 你运行的是哪个版本？只有ekf的吗？

对的对的。

**Comment by plumewind** [comment]
你试试最新版本的，ekf - ukf，我刚才试着运行里面的ekf部分是没有问题的

**Comment by hodgechung** [comment]
你好,我跑ekf - ukf版本也遇到了这个问题.

**Comment by hodgechung** [comment]
> `simulator: /usr/local/include/eigen3/Eigen/src/Core/Redux.h:413: typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_max_op<double, double>; Derived = Eigen::PartialReduxExpr<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::Matrix<double, -1, -1> >, Eigen::internal::member_sum<double>, 0>; typename Eigen::internal::traits<T>::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.
> [simulator-2] process has died [pid 14520, exit code -6, cmd /home/minghua/catkin_ekf/devel/lib/slam_simulator/simulator __name:=simulator __log:=/home/minghua/.ros/log/1fdc52cc-a153-11e9-80e2-000c29d62a5d/simulator-2.log].
> log file: /home/minghua/.ros/log/1fdc52cc-a153-11e9-80e2-000c29d62a5d/simulator-2*.log
> 
> `
> 作者你好，当我运行ekf的时候出现上述错误，不知道该如何解决。麻烦您能帮忙看一下吗？打开rviz之后就挂掉了。

可以参考#4
